services:

  postgres:
    image: postgres:16-alpine
    container_name: pizza_corrida_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    image: pizza_corrida_api
    container_name: pizza_corrida_api
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: ./frontend
    image: pizza_corrida_frontend
    container_name: pizza_corrida_frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

volumes:
  pgdata:
