services:

  postgres:
    image: postgres:16-alpine
    container_name: pizza_corrida_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pizza_corrida
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pizza_corrida"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    image: pizza_corrida_api
    container_name: pizza_corrida_api
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: ./frontend
    image: pizza_corrida_frontend
    container_name: pizza_corrida_frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

  prometheus:
    image: prom/prometheus:latest
    container_name: pizza_corrida_prometheus

    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

  grafana:
    image: grafana/grafana:latest
    container_name: pizza_corrida_grafana

    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: pizza_corrida_cadvisor

    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    privileged: true

  node-exporter:
    image: prom/node-exporter:latest
    container_name: pizza_corrida_node_exporter

    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'

  jenkins:
    build:
      context: ./jenkins
      args:
        DOCKER_GID: ${DOCKER_GID:-984}
    image: pizza_corrida_jenkins
    container_name: pizza_corrida_jenkins

    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  pgdata:
  jenkins_data:
  prometheus_data:
  grafana_data:
